---
- name:             Create admin user for all database
  mongodb_user:
    database :      "admin"
    name :          "{{ mongodb_user_admin_name }}"
    password:       "{{ mongodb_user_admin_password }}"
    state:          present
    roles:          "{{ mongodb_user_admin_roles }}"
  ignore_errors:    no

- name:             Create users for {{ mongodb_foobar_user_database }} database
  mongodb_user:
    database :      "{{ mongodb_foobar_user_database }}"
    name :          "{{ mongodb_foobar_user_name }}"
    password:       "{{ mongodb_foobar_user_password }}"
    state:          present
    roles:          "{{ mongodb_foobar_user_roles }}"
    login_database: "admin"
    login_port:     "{{ mongodb_login_port }}"
    login_user:     "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
  ignore_errors:  no

- name:             Create users john for {{ mongodb_foobar_user_database }} database
  mongodb_user:
    database:     "{{ mongodb_foobar_user_database }}"
    name:         john
    password:     "12345"
    roles:        read
    state:        present
    login_database: "admin"
    login_port:     "{{ mongodb_login_port }}"
    login_user:     "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"

- name:             Create users doe for {{ mongodb_foobar_user_database }} database
  mongodb_user:
    database:     "{{ mongodb_foobar_user_database }}"
    name:         doe
    password:     "12345"
    roles:        readWrite,dbAdmin,userAdmin
    state:        present
    login_database: "admin"
    login_port:     "{{ mongodb_login_port }}"
    login_user:     "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
